import LocalizedStrings from 'react-native-localization';

export let strings = new LocalizedStrings({
    bn: {
        quranSources: "কোরান উৎস",
        searchChapterHint: "একটি সূরা অনুসন্ধান করুন..",
        searchVerseHint: "একটি আয়াত অনুসন্ধান করুন..",
        chapterCouldntFind: "সূরা খুঁজে পাওয়া যায়নি।",
        verseCouldntFind: "আয়াত খুঁজে পাওয়া যায়নি।",
        translation: "অনুবাদ",
        dontKnowHowOpen: "এই URL টি কিভাবে খুলব জানি না",
        noSavedChapter: "কোনও সংরক্ষিত সূরা নেই",
        noSavedVerse: "কোনও সংরক্ষিত আয়াত নেই",
        noSavedBookmark: "কোন সংরক্ষিত বুকমার্ক নেই.",
        options: "বিকল্পসমূহ",
        close: "বন্ধ করুন",
        chapter: "সূরা",
        verse: "আয়াত",
        preferences: "পছন্দ",
        darkMode: 'অন্ধকার মোড',
        fontSelection: 'ফন্ট নির্বাচন',
        app: 'অ্যাপ',
        bookmark: "বুকমার্ক",
        rateApp: 'অ্যাপটি রেট করুন',
        share: "ভাগ করুন",
        requestAndComplaints: 'অনুরোধ এবং অভিযোগ',
        error: "ত্রুটি",
        sharedWith: "দ্বারা শেয়ার করা",
        quranVerse: "কোরানের আয়াত",
        save: "সংরক্ষণ করুন",
        unSave: "সংরক্ষিত করুন না",
        verses: "আয়াতসমূহ",
        copy: "অনুলিপি",
        home: "হোম",
        saved: "সংরক্ষিত",
        settings: "সেটিংস",
        small: "ছোট",
        normal: "সাধারণ",
        mid: "মধ্যম",
        big: "বড়"
    },
    en: {
        quranSources: "Quran Sources",
        searchChapterHint: "Search for a chapter..",
        searchVerseHint: "Search for a verse..",
        chapterCouldntFind: "Chapter couldn't find.",
        verseCouldntFind: "Verse couldn't find.",
        translation: "Translation",
        dontKnowHowOpen: "Don't know how to open this URL",
        noSavedChapter: "No Saved Chapter",
        noSavedVerse: "No Saved Verse",
        options: "OPTIONS",
        close: "CLOSE",
        chapter: "Chapter",
        verse: "Verse",
        preferences: "Preferences",
        darkMode: 'Dark mode',
        fontSelection: 'Font Selection',
        app: 'App',
        bookmark: "Bookmark",
        rateApp: 'Rate the App',
        share: "Share",
        requestAndComplaints: 'Requests and complaints',
        error: "Error",
        sharedWith: "Shared by",
        quranVerse: "Quran Verse",
        save: "Save",
        unSave: "Unsave",
        verses: "verses",
        copy: "Copy",
        home: "Home",
        saved: "Saved",
        settings: "Settings",
        small: "Small",
        normal: "Normal",
        mid: "Mid",
        big: "Big",
        noSavedBookmark: "No saved bookmark."
    },
    es: {
        quranSources: "Fuentes del Corán",
        searchChapterHint: "Buscar un capítulo..",
        searchVerseHint: "Buscar un verso..",
        chapterCouldntFind: "No se pudo encontrar el capítulo.",
        verseCouldntFind: "No se pudo encontrar el verso.",
        translation: "Traducción",
        dontKnowHowOpen: "No sé cómo abrir esta URL",
        noSavedChapter: "No hay capítulos guardados",
        noSavedVerse: "No hay versos guardados",
        noSavedBookmark: "No hay marcadores guardados.",
        options: "OPCIONES",
        close: "CERRAR",
        chapter: "Capítulo",
        verse: "Verso",
        preferences: "Preferencias",
        darkMode: 'Modo oscuro',
        fontSelection: 'Selección de fuente',
        app: 'Aplicación',
        bookmark: "Marcador",
        rateApp: 'Calificar la aplicación',
        share: "Compartir",
        requestAndComplaints: 'Solicitudes y quejas',
        error: "Error",
        sharedWith: "Compartido por",
        quranVerse: "Verso del Corán",
        save: "Guardar",
        unSave: "Desguardar",
        verses: "versos",
        copy: "Copiar",
        home: "Inicio",
        saved: "Guardado",
        settings: "Configuraciones",
        small: "Pequeño",
        normal: "Normal",
        mid: "Mediano",
        big: "Grande"
    },
    fr: {
        quranSources: "Sources du Coran",
        searchChapterHint: "Rechercher un chapitre..",
        searchVerseHint: "Rechercher un verset..",
        chapterCouldntFind: "Impossible de trouver le chapitre.",
        verseCouldntFind: "Impossible de trouver le verset.",
        translation: "Traduction",
        dontKnowHowOpen: "Je ne sais pas comment ouvrir cette URL",
        noSavedChapter: "Aucun chapitre enregistré",
        noSavedVerse: "Aucun verset enregistré",
        noSavedBookmark: "Il n'y a pas de favoris enregistrés.",
        options: "OPTIONS",
        close: "FERMER",
        chapter: "Chapitre",
        verse: "Verset",
        preferences: "Préférences",
        darkMode: 'Mode sombre',
        fontSelection: 'Sélection de police',
        app: 'Application',
        bookmark: "Signet",
        rateApp: 'Noter l\'application',
        share: "Partager",
        requestAndComplaints: 'Demandes et plaintes',
        error: "Erreur",
        sharedWith: "Partagé par",
        quranVerse: "Verset du Coran",
        save: "Enregistrer",
        unSave: "Supprimer l'enregistrement",
        verses: "versets",
        copy: "Copier",
        home: "Accueil",
        saved: "Enregistré",
        settings: "Paramètres",
        small: "Petit",
        normal: "Normal",
        mid: "Moyen",
        big: "Grand"
    },
    id: {
        quranSources: "Sumber Quran",
        searchChapterHint: "Cari surat..",
        searchVerseHint: "Cari ayat..",
        chapterCouldntFind: "Surat tidak dapat ditemukan.",
        verseCouldntFind: "Ayat tidak dapat ditemukan.",
        translation: "Terjemahan",
        dontKnowHowOpen: "Tidak tahu cara membuka URL ini",
        noSavedChapter: "Tidak ada Surat Tersimpan",
        noSavedVerse: "Tidak ada Ayat Tersimpan",
        noSavedBookmark: "Tidak ada bookmark yang disimpan.",
        options: "OPSI",
        close: "TUTUP",
        chapter: "Surat",
        verse: "Ayat",
        preferences: "Preferensi",
        darkMode: 'Mode Gelap',
        fontSelection: 'Pemilihan Font',
        app: 'Aplikasi',
        bookmark: "Bookmark",
        rateApp: 'Beri Nilai Aplikasi',
        share: "Bagikan",
        requestAndComplaints: 'Permintaan dan Keluhan',
        error: "Kesalahan",
        sharedWith: "Dibagikan oleh",
        quranVerse: "Ayat Quran",
        save: "Simpan",
        unSave: "Batal Simpan",
        verses: "ayat",
        copy: "Salin",
        home: "Beranda",
        saved: "Tersimpan",
        settings: "Pengaturan",
        small: "Kecil",
        normal: "Normal",
        mid: "Sedang",
        big: "Besar"
    },
    ru: {
        quranSources: "Источники Корана",
        searchChapterHint: "Поиск главы..",
        searchVerseHint: "Поиск стиха..",
        chapterCouldntFind: "Не удалось найти главу.",
        verseCouldntFind: "Не удалось найти стих.",
        translation: "Перевод",
        dontKnowHowOpen: "Не знаю, как открыть этот URL",
        noSavedChapter: "Нет сохраненных глав",
        noSavedVerse: "Нет сохраненных стихов",
        noSavedBookmark: "Нет сохраненных закладок.",
        options: "ОПЦИИ",
        close: "ЗАКРЫТЬ",
        chapter: "Глава",
        verse: "Стих",
        preferences: "Настройки",
        darkMode: 'Темный режим',
        fontSelection: 'Выбор шрифта',
        app: 'Приложение',
        bookmark: "Закладка",
        rateApp: 'Оценить приложение',
        share: "Поделиться",
        requestAndComplaints: 'Запросы и жалобы',
        error: "Ошибка",
        sharedWith: "Поделился",
        quranVerse: "Аят Корана",
        save: "Сохранить",
        unSave: "Не сохранять",
        verses: "стихи",
        copy: "Копировать",
        home: "Главная",
        saved: "Сохранено",
        settings: "Настройки",
        small: "Маленький",
        normal: "Обычный",
        mid: "Средний",
        big: "Большой"
    },
    sv: {
        quranSources: "Koran Källor",
        searchChapterHint: "Sök efter ett kapitel..",
        searchVerseHint: "Sök efter en vers..",
        chapterCouldntFind: "Kunde inte hitta kapitlet.",
        verseCouldntFind: "Kunde inte hitta versen.",
        translation: "Översättning",
        dontKnowHowOpen: "Vet inte hur man öppnar denna URL",
        noSavedChapter: "Inget sparad kapitel",
        noSavedVerse: "Ingen sparad vers",
        noSavedBookmark: "Det finns inga sparade bokmärken.",
        options: "ALTERNATIV",
        close: "STÄNG",
        chapter: "Kapitel",
        verse: "Vers",
        preferences: "Preferenser",
        darkMode: 'Mörkt läge',
        fontSelection: 'Typsnittsval',
        app: 'App',
        bookmark: "Bokmärke",
        rateApp: 'Betygsätt appen',
        share: "Dela",
        requestAndComplaints: 'Begäranden och klagomål',
        error: "Fel",
        sharedWith: "Delad av",
        quranVerse: "Koranvers",
        save: "Spara",
        unSave: "Ta bort sparade",
        verses: "vers",
        copy: "Kopiera",
        home: "Hem",
        saved: "Sparad",
        settings: "Inställningar",
        small: "Liten",
        normal: "Normal",
        mid: "Medium",
        big: "Stor"
    },
    tr: {
        quranSources: "Kuran Kaynakları",
        searchChapterHint: "Sure ara..",
        searchVerseHint: "Ayet ara..",
        chapterCouldntFind: "Sure bulunamadı.",
        verseCouldntFind: "Ayet bulunamadı.",
        translation: "Çeviri",
        dontKnowHowOpen: "Bu URL'yi nasıl açacağımı bilmiyorum",
        noSavedChapter: "Kayıtlı Sure Yok",
        noSavedVerse: "Kayıtlı Ayet Yok",
        noSavedBookmark: "Kaydedilmiş yer işareti yok.",
        options: "SEÇENEKLER",
        close: "KAPAT",
        chapter: "Sure",
        verse: "Ayet",
        preferences: "Tercihler",
        darkMode: 'Koyu Mod',
        fontSelection: 'Yazı Tipi Seçimi',
        app: 'Uygulama',
        bookmark: "Yer İşareti",
        rateApp: 'Uygulamayı Derecelendir',
        share: "Paylaş",
        requestAndComplaints: 'Talepler ve Şikayetler',
        error: "Hata",
        sharedWith: "Tarafından paylaşıldı",
        quranVerse: "Kuran Ayeti",
        save: "Kaydet",
        unSave: "Kaydı Sil",
        verses: "ayet",
        copy: "Kopyala",
        home: "Ana Sayfa",
        saved: "Kaydedilen",
        settings: "Ayarlar",
        small: "Küçük",
        normal: "Normal",
        mid: "Orta",
        big: "Büyük"
    },
    ur: {
        quranSources: "قرآن کے ذرائع",
        searchChapterHint: "ایک باب تلاش کریں..",
        searchVerseHint: "ایک آیت تلاش کریں..",
        chapterCouldntFind: "باب نہیں مل سکا۔",
        verseCouldntFind: "آیت نہیں مل سکی۔",
        translation: "ترجمہ",
        dontKnowHowOpen: "اس URL کو کیسے کھولنا ہے مجھے نہیں معلوم",
        noSavedChapter: "کوئی محفوظ شدہ باب نہیں",
        noSavedVerse: "کوئی محفوظ شدہ آیت نہیں",
        noSavedBookmark: "کوئی محفوظ کردہ بک مارکس نہیں ہیں۔",
        options: "اختیارات",
        close: "بند کریں",
        chapter: "باب",
        verse: "آیت",
        preferences: "ترجیحات",
        darkMode: 'تاریک موڈ',
        fontSelection: 'فونٹ کا انتخاب',
        app: 'ایپ',
        bookmark: "بک مارک",
        rateApp: 'ایپ کو درج کریں',
        share: "شیئر کریں",
        requestAndComplaints: 'درخواستیں اور شکایات',
        error: "خطا",
        sharedWith: "کے ساتھ شیئر کیا گیا",
        quranVerse: "قرآنی آیت",
        save: "محفوظ کریں",
        unSave: "محفوظ نہ کریں",
        verses: "آیات",
        copy: "کاپی",
        home: "ہوم",
        saved: "محفوظ",
        settings: "ترتیبات",
        small: "چھوٹا",
        normal: "عام",
        mid: "درمیانی",
        big: "بڑا"
    },
    zh: {
        quranSources: "古兰经来源",
        searchChapterHint: "搜索章节..",
        searchVerseHint: "搜索经文..",
        chapterCouldntFind: "无法找到章节。",
        verseCouldntFind: "无法找到经文。",
        translation: "翻译",
        dontKnowHowOpen: "不知道如何打开此网址",
        noSavedChapter: "没有保存的章节",
        noSavedVerse: "没有保存的经文",
        noSavedBookmark: "没有保存的书签。",
        options: "选项",
        close: "关闭",
        chapter: "章",
        verse: "经文",
        preferences: "偏好设置",
        darkMode: '暗模式',
        fontSelection: '字体选择',
        app: '应用程序',
        bookmark: "书签",
        rateApp: '给应用程序评分',
        share: "分享",
        requestAndComplaints: '请求和投诉',
        error: "错误",
        sharedWith: "分享自",
        quranVerse: "古兰经经文",
        save: "保存",
        unSave: "取消保存",
        verses: "经文",
        copy: "复制",
        home: "首页",
        saved: "已保存",
        settings: "设置",
        small: "小",
        normal: "正常",
        mid: "中",
        big: "大"
    }
});
